export const articles = [
  {
    title: 'Lorem ipsum dolor sit amet',
    author: 'Judyta Ciesielska',
    content:
      'Sit labore lorem no dolor tempor invidunt diam. Stet amet eos no ut takimata labore, kasd et ea elitr et. Lorem sit diam est eos ut amet magna. Diam lorem lorem erat no lorem. <br><br> Sea dolor sit consetetur dolor ipsum et voluptua ut sit, labore sed sed consetetur consetetur kasd voluptua nonumy sadipscing. Lorem eos sed elitr justo ea takimata ipsum sed. Diam lorem diam clita elitr amet duo ipsum et sit, labore justo sit amet aliquyam voluptua invidunt magna, vero ipsum sed consetetur et sit et. Kasd rebum sit eos erat et ut, et amet at diam labore sanctus, amet sit consetetur aliquyam rebum et eirmod magna sed erat. Sit et sadipscing rebum vero et clita, sit ea gubergren no et et eos aliquyam sanctus et, eirmod sed amet gubergren ut tempor diam. Rebum et at magna magna eirmod. <br><br> Et labore lorem tempor et justo aliquyam. Amet ut duo et at rebum eos tempor amet voluptua, tempor dolores sit voluptua kasd. Lorem justo ea accusam justo labore tempor amet eos, amet et sit lorem labore tempor aliquyam. Eirmod sit nonumy rebum magna sit ea, dolor kasd takimata at est et lorem. Ea sed nonumy diam et. No erat at est labore. Lorem no dolor kasd sed invidunt duo diam stet, amet nonumy no nonumy elitr eirmod amet no sit. Lorem sed et justo lorem et aliquyam accusam nonumy. Erat diam kasd et dolores dolore. Gubergren kasd consetetur gubergren sed consetetur takimata voluptua clita, erat sed justo ipsum nonumy consetetur nonumy ut, rebum dolor sadipscing et sadipscing voluptua.<br><br> Accusam ipsum amet stet dolor eos sea ipsum sea. Ea sanctus duo dolor diam dolor eirmod takimata, elitr no voluptua ipsum invidunt.',
  },
  {
    title: 'Nonumy et diam amet clita dolores',
    author: 'Katarzyna Markiewicz',
    content:
      'Lorem duo kasd eirmod at dolores tempor. Diam invidunt eos gubergren dolor lorem dolore et. Justo invidunt sit ipsum magna kasd et eos et eirmod, et ipsum at accusam clita lorem erat et. <br><br> Erat voluptua nonumy et sanctus justo et sanctus takimata, sit consetetur sadipscing sit invidunt. Dolores ipsum sadipscing ipsum sea dolor ea et consetetur eirmod. Stet at est amet sadipscing tempor no no sadipscing, kasd erat et ut amet kasd et rebum justo dolores, stet eirmod lorem accusam dolores sea erat lorem et. Voluptua consetetur sit diam invidunt elitr dolor vero sadipscing, lorem diam ea sit takimata labore et kasd. Amet clita rebum gubergren justo amet amet at gubergren tempor.<br><br> Consetetur labore sed aliquyam accusam labore et. Voluptua et magna et takimata voluptua no ea gubergren diam. Ipsum et dolor et consetetur. Et dolor magna ea sit sed, sanctus lorem est est dolor rebum at est aliquyam magna, nonumy et et sadipscing elitr eirmod dolore sed. Labore sadipscing sit ea aliquyam lorem dolores sanctus, sed ut tempor eirmod diam dolor at et ipsum. Invidunt eos labore lorem dolor dolor vero amet ipsum, stet tempor ut lorem eirmod, ut justo ea dolores eirmod eirmod dolor. Ipsum diam justo sadipscing justo. Erat eirmod no nonumy takimata et amet lorem nonumy, ipsum gubergren dolor dolor invidunt invidunt kasd ipsum, lorem sit et ipsum eirmod et nonumy kasd, sanctus et ipsum et sit erat sed, no lorem eirmod est consetetur vero accusam.',
  },
  {
    title: 'Eos et aliquyam amet',
    author: 'Judyta Ciesielska',
    content:
      'Diam sed voluptua accusam gubergren et, et nonumy stet amet consetetur sit lorem erat ut. Sed dolores elitr aliquyam aliquyam sadipscing amet sed sit, vero sed erat no duo. <br><br> Clita sed et ea et clita amet diam, erat dolor rebum tempor est dolore, sit et accusam et dolor sit sit lorem, duo consetetur magna et sit duo at, sed lorem sea ea elitr sed kasd tempor dolor sed, dolor elitr dolor ipsum justo accusam clita kasd sit. Dolore et voluptua accusam takimata amet clita takimata, magna elitr amet sed kasd magna lorem sit, accusam invidunt est stet et duo, amet sed takimata amet sit takimata diam at. At dolore sit vero amet dolor dolores et ea, invidunt sit dolor dolore diam ipsum sanctus, eos sed amet sadipscing at. Aliquyam rebum stet amet labore ipsum tempor aliquyam gubergren. Duo justo vero eirmod elitr est justo elitr sanctus duo, lorem lorem sea stet sanctus voluptua dolore. Dolore et et et sed invidunt justo voluptua, sea invidunt tempor gubergren diam duo aliquyam lorem. Ipsum erat et dolores amet diam. Kasd sed sea at elitr et sanctus sed erat et. Diam diam nonumy dolores sed eirmod, eos gubergren dolore sanctus stet at amet at et.<br><br> Magna diam tempor et voluptua no et labore stet ipsum, eos dolor accusam aliquyam et aliquyam invidunt aliquyam nonumy dolore. Accusam eirmod et diam sea dolor et ut eirmod, dolor sit sed eirmod sed magna. Gubergren clita dolore voluptua clita, ut dolor magna labore amet sit takimata at takimata. Magna ut diam invidunt invidunt ipsum, at accusam aliquyam sit stet, sanctus justo dolor voluptua diam. Eirmod est sanctus clita rebum dolore, rebum dolores gubergren dolor diam lorem eirmod erat ipsum. Sed consetetur sea dolor sanctus est dolor kasd dolor eos. Eirmod et sed duo eos, sit dolor ipsum est ut ut voluptua gubergren ipsum. Erat accusam diam nonumy sit sanctus gubergren dolore. Aliquyam eirmod kasd justo at justo labore kasd et, diam sed sadipscing voluptua sadipscing duo et et diam erat, diam tempor eirmod invidunt takimata tempor consetetur, amet sadipscing consetetur at et elitr no sea diam. Takimata ipsum tempor ut sed amet lorem elitr. Ipsum et sadipscing ea takimata elitr voluptua dolor dolore, est sed nonumy ipsum sed, at dolor labore voluptua sit, invidunt dolores magna sea eirmod.',
  },
]
